### ISSUE TITLE
unexpected behaviors

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-cesm#13]
I am starting to work with `intake_cesm`, but find that it does not behave as expected.

First point: the query function seems like it might not be working correctly. For instance, let's say I want to get data for the variable `FG_CO2` for experiments '20C' and 'RCP85'
```
>>> cat = collection.search(experiment=['20C', 'RCP85'], component='ocn', variable='FG_CO2')
```
Seems to work, but when I do 
```
>>> cat.results.files.tolist()
```
I see that the list includes files from the control integration (`experiment='CTRL'`):
```
['/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/FG_CO2/b.e11.B1850C5CN.f09_g16.005.pop.h.FG_CO2.040001-049912.nc',
 '/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/FG_CO2/b.e11.B1850C5CN.f09_g16.005.pop.h.FG_CO2.050001-059912.nc',
 '/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/FG_CO2/b.e11.B1850C5CN.f09_g16.005.pop.h.FG_CO2.060001-069912.nc',
 '/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/FG_CO2/b.e11.B1850C5CN.f09_g16.005.pop.h.FG_CO2.070001-079912.nc',
....
```
So that's unexpected.

Second issue, there is some subtlety in loading files into `xarray.Datasets`. 
```
ds = cat.to_xarray()
```
returns a dataset, but it appears to have concatenated *everything* along a time dimension! 
```
<xarray.Dataset>
Dimensions:               (d2: 2, lat_aux_grid: 395, moc_comp: 3, moc_z: 61, nlat: 384, nlon: 320, time: 96300, transport_comp: 5, transport_reg: 2, z_t: 60, z_t_150m: 15, z_w: 60, z_w_bot: 60, z_w_top: 60)
Coordinates:
  * lat_aux_grid          (lat_aux_grid) float32 -79.48815 -78.952896 ... 90.0
  * moc_z                 (moc_z) float32 0.0 1000.0 ... 525000.94 549999.06
  * z_t                   (z_t) float32 500.0 1500.0 ... 512502.8 537500.0
  * z_t_150m              (z_t_150m) float32 500.0 1500.0 ... 13500.0 14500.0
  * z_w                   (z_w) float32 0.0 1000.0 2000.0 ... 500004.7 525000.94
  * z_w_bot               (z_w_bot) float32 1000.0 2000.0 ... 549999.06
  * z_w_top               (z_w_top) float32 0.0 1000.0 ... 500004.7 525000.94
  * time                  (time) float64 1.46e+05 1.461e+05 ... 7.669e+05
Dimensions without coordinates: d2, moc_comp, nlat, nlon, transport_comp, transport_reg
Data variables:
    ANGLE                 (time, nlat, nlon) float64 dask.array<shape=(96300, 384, 320), chunksize=(1200, 384, 320)>
    ANGLET                (time, nlat, nlon) float64 dask.array<shape=(96300, 384, 320), chunksize=(1200, 384, 320)>
    DXT                   (time, nlat, nlon) float64 dask.array<shape=(96300, 384, 320), chunksize=(1200, 384, 320)>
...
```
The appropriate behavior would be to concatenate in time for each experiment, then concatenate the ensembles across a new "ensemble" dimension. 

The first point above (unexpected inclusion of an unspecified experiment) seems like a bug. 

The second point is probably a feature, at least for now: users have to specify queries that resolve into a sensible dataset.

**Comment by andersy005** [comment]
Thank you @matt-long

Issue 1) is definitely a bug. For issue 2), I concur with you. We should concatenate in time for each experiment, then concatenate the ensembles across a new "ensemble" dimension. I will fix these soon

**Comment by andersy005** [comment]
Thank you for looking into this, @matt-long! `urlpath` doesn't need to be a list . The only attribute that it is important is `self_ds`.  We would just have to change the behavior of `open_dataset` to set `self_ds`.

If 
```python
urlpath = get_subset(self.collection, self.query).files.tolist()
```
is changed to 
```python
urlpath = get_subset(self.collection, self.query)
```
we can manipulate the returned dataframe in a way you described above:
>For the dataset concatenation issue, it seems to me that we can simply modify the _open_dataset method in CesmSource to loop over ensembles.

**Comment by matt-long** [comment]
@andersy005: I have a branch with some (partial) fixes.

https://github.com/matt-long/intake-cesm/tree/bug_fix1

**The catalog query issue**
The problem was that when a query contains a `list`, entries in that list should be treated with an `OR` condition, not an `AND` condition. My implementation may reveal my relative ignorance of pandas...but it works.

**The open_dataset issue**
I have prototyped a change in `_open_dataset`...but this issue is more complicated.

The strategy is to loop over `ensembles` and for each `variable` concatenate in `time`, and then `merge` over all variables. 

Here is a nice test case that works with my new code.
```
import intake
collection = intake.open_cesm_metadatastore('cesm1_le')
cat = collection.search(experiment=['RCP85', '20C'], component='ocn', variable='FG_CO2', ensemble=[25, 26])
ds = cat.to_xarray()
```
This works because these two ensembles have the same date ranges in their files. This example should fail.
```
cat = collection.search(experiment=['RCP85', '20C'], component='ocn', variable='FG_CO2', ensemble=[1, 2])
ds = cat.to_xarray()
```
because ensemble 1 goes from 1850-2100, not 1920-2100 like the others.

We would need to check the time range in the files and use only overlapping portions. Alternatively, we could test whether the query can be assembled in this way—and if not require an additional argument specifying the time range to use. 

The CESM-LE presents some challenges; there may be many others. Another that I know about is when lossy-compression has been applied to coordinate variables. This causes `xr.concat` with `data_vars` specified to fail.

**Comment by matt-long** [comment]
I am closing this as #17 mostly addressing it. The issues with `to_xarray()` deserve a more focused forum for discussion.
