### ISSUE TITLE
test coverage for catalog generation

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-cesm#19]
This is easy to test in situ on Cheyenne (or in other places) but hard in the CI framework. 

Can we break out tests that should not run in the CI space, but should when there is access to the data necessary to build a catalog?

**Comment by andersy005** [comment]
Another solution is creating some `toy` datasets and using these for testing purposes. I did something similar to this for `intake-cmip`.  I will work on this

**Comment by matt-long** [comment]
Could also curate a file with a list of paths to be parsed and enable reading that file as a virtual `walk` of a directory structure. This would enable testing everything down stream of the actual listing of files.

**Comment by andersy005** [comment]
Fixed in #28
