### ISSUE TITLE
harmonize types

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-cesm#21]
From the user perspective, our various classes are confusing. 

Should `manage_collections.CESMCollections` return a type of `CesmMetadataStoreCatalog`?

This would feel more natural. The return object from a freshly build collection could be query, etc. directly without having to re-invoke
```
collection = intake.open_cesm_metadatastore(collection_name)
```
for instance.

**Comment by andersy005** [comment]
@matt-long, when I look at both classes, it appears that they are accomplishing two different things (One is being used to build the catalog, whereas the other is used to work with the built catalog). 
- As a user, you would use functionality from `CesmMetadataStoreCatalog` more often than `CESMCollections` right? And if this is the case, wouldn't be better to keep the two classes separate?
- One advantage of separating the two classes is that it would be easy to refactor, extend them in the near future if they are kept separate. Having them into one huge class might introduce some complexity. However, I think that there's room for consolidating the two classes into one class. 

Let me know what you think and how you would like us to consolidate the two classes into one.

**Comment by matt-long** [comment]
I think the implementation under the hood should be considered carefully given the points you've raised; however, I think from the *user* perspective it should appear more homogenous that what we have now.  Here's a workflow that I envision.

A project (like for writing a manuscript) will have a "manage_collections" notebook or script where the collections are built and maintained.

First step might be to build the initial collection:
```python
collection_type_def_file = 'cesm_definitions.yml'
collection_input_file = 'collection_input_cesm1_le.yml'
col = intake_cesm.CESMCollections(collection_input_file=collection_input_file,
                                  collection_type_def_file=collection_type_def_file,
                                  overwrite_existing=False, 
                                  include_cache_dir=True)
```
Ok, now I want to use that collection....wait! It's a different type? 
```python
col = intake.open_cesm_metadatastore('cesm1_le')
```
I think that is unnecessary and confusing. I haven't thought through all the details of implementation, but I think it's pretty clear the interface is too cluttered.

**Comment by andersy005** [comment]
> it's pretty clear the interface is too cluttered.

I concur with you on this. 

However, thinking about it a moment more, I think the two classes have less in common, and separating them is probably going to make our work easier. It is true to that from a user's perspective, it is better to only deal with one object/class. However, I favor the current behavior. Would it be useful to change the name of `CesmCollections` to a more explicit name `CesmCollectionsBuilder`?

By the way, adding `name` attribute to the class:

```python
class CESMCollectionsBuilder(object):
   name = 'cesm_collections_builder'
    def __init__(
        self,
        collection_input_file,
        collection_type_def_file,
        overwrite_existing=False,
        include_cache_dir=False,
    ):
```

would allow you to do this:

```python
col = intake.open_cesm_collections_builder(collection_input_file=collection_input_file,
                                  collection_type_def_file=collection_type_def_file,
                                  overwrite_existing=False, 
                                  include_cache_dir=True)
```

**Comment by matt-long** [comment]
What if the `cesm_metadatastore` class had a `build_collection` method and the interface supported passing in args to enable and trigger a build?

I could imagine something like this
```Python
build_dict = {'collection_input_file': collection_input_file,
              'collection_type_def_file': collection_type_def_file,
              'overwrite_existing': False, 
              'include_cache_dir': True}
col = intake.open_cesm_metadatastore('cesm1_le', build_kwargs=build_dict)
```
Under this approach, the `build_collections` method would be move from `CESMCollections` to `CesmMetadataStoreCatalog`, which I think is appropriate. We have a theoretical notion of extensibility to collection types other than CESM: CMIP could (should?!) be one of those. I think we should seriously consider consolidating efforts on these two packages soon.

One thing I've decided might be nice is to supply the name of the collection via user input, rather than rely on the input file. This makes more sense from the user perspective as they can see in the code what the collection is named, versus having to go check a .yml file.

Also, I would like to eliminate the requirement to pass a `collection_type_def_file` file, related to #18. There are use cases, however, where setting elements currently in this file is desirable. So I propose we merge that file into the input file and have defaults in the code that can be extended/overridden by this input.

**Comment by andersy005** [comment]
I like this approach of moving `build_collections` method to `CesmMetadataStoreCatalog`.

> We have a theoretical notion of extensibility to collection types other than CESM: CMIP could (should?!) be one of those. I think we should seriously consider consolidating efforts on these two packages soon.

I agree. It looks like most necessary pieces for consolidating the two packages into one package are taking shape. And it is probably time to revive this conversation.
