### ISSUE TITLE
Bug in `manage_collections.py`

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-cesm#27]
A while back I changed `_extract_cesm_date_str` method to something I thought was  simple and correct. However, today when generating CESM collection catalog from files with `hsi`, I got this error:

```python-traceback
/gpfs/u/home/abanihi/devel/intake-cesm/intake_cesm/manage_collections.py in _build_cesm_collection_df_files(self, resource_key, resource_type, direct_access, filelist)
    233 
    234         for f in tqdm(filelist):
--> 235             fileparts = self._cesm_filename_parts(os.path.basename(f), self.component_streams)
    236 
    237             if fileparts is None:

/gpfs/u/home/abanihi/devel/intake-cesm/intake_cesm/manage_collections.py in _cesm_filename_parts(self, filename, component_streams)
    169 
    170         # define lists of stream strings
--> 171         datestr = self._extract_cesm_date_str(filename)
    172 
    173         for component, streams in component_streams.items():

/gpfs/u/home/abanihi/devel/intake-cesm/intake_cesm/manage_collections.py in _extract_cesm_date_str(self, filename)
    162     def _extract_cesm_date_str(self, filename):
    163         """Extract a datastr from file name."""
--> 164         b = filename.split(".")[-2]
    165         return b
    166 

IndexError: list index out of range
```

@matt-long, I was wondering whether you ever saw this error before? It appears that everything in `build_collections` notebook ran smoothly for you. I am not sure why It breaks on my part.

**Comment by andersy005** [comment]
My change:
```python
def _extract_cesm_date_str(self, filename):
        """Extract a datastr from file name."""
        b = filename.split(".")[-2]
        return b
```
is clearly not robust....

Putting back 

```python
def _extract_cesm_date_str(filename):
    '''Extract a datastr from file name.'''

    # must be in order of longer to shorter strings
    # TODO: make this function return a date object as well as string
    # should it also return a freq?
    datestrs = [r'\d{12}Z-\d{12}Z',
                r'\d{10}Z-\d{10}Z',
                r'\d{8}-\d{8}',
                r'\d{6}-\d{6}',
                r'\d{4}-\d{4}']

    for datestr in datestrs:
        match = re.compile(datestr).findall(filename)
        if match:
            return match[0]

    raise ValueError(f'unable to match date string: {filename}')
```
breaks the rest of the code though.

**Comment by matt-long** [comment]
@andersy005 your code should work if the file conforms to the expected pattern. I am not sure when this change came in: I presume I was running with it yesterday? Did you change anything else? The HSI command puts all its output (as far as I can tell) to stderr, so there are both files AND error messages in the returned list.  Typical errors look like this
```
*** hpss_Opendir: Access denied [-13: HPSS_EACCES]
    /CCSM/csm/CESM-CAM5-BGC-LE/cases/b.e11.B20TRLENS_RCP85.f09_g16.xaer.017/ocn/hist
*** hpss_Opendir: Access denied [-13: HPSS_EACCES]
    /CCSM/csm/CESM-CAM5-BGC-LE/cases/b.e11.B20TRLENS_RCP85.f09_g16.xaer.018/ocn/hist
*** hpss_Opendir: Access denied [-13: HPSS_EACCES]
    /CCSM/csm/CESM-CAM5-BGC-LE/cases/b.e11.B20TRLENS_RCP85.f09_g16.xaer.019/ocn/hist
```
Both approaches have shortcomings. The regex approach might find more than one match. Perhaps we should have 
```python
   return match[-1]
```
Your approach might be more robust and could be inured against the error you are getting by testing the length of the list returned by `split`. 

POP also writes files like this: "b.e11.B20TRLENS_RCP85.f09_g16.xaer.003.pop.h.once.nc" where the date string is "once". Your code should handle this nicely, the regex approach would fail as currently implemented.

**Comment by matt-long** [comment]
It would be good to print a message with the filename so we can understand what we are missing.
